#!/bin/bash
# verify-decrypt-setup.sh - Is the decrypt CLI genuinely ready?
#
# Single source of truth for "setup actually succeeded", used to gate the
# /oss:login success banner and the auto-hook's "ready" message. It declares
# success ONLY when the binary actually RUNS and credentials.enc exists; on any
# failure it surfaces the binary's real stderr and exits non-zero — never a
# false "Setup Complete".
#
# Usage:   ~/.oss/hooks/verify-decrypt-setup.sh
# Returns: 0 = decrypt CLI runs AND credentials configured
#          1 = not ready (message explains why; binary stderr surfaced)

set -uo pipefail

OSS_DIR="${HOME}/.oss"
OSS_DECRYPT="${OSS_DIR}/bin/oss-decrypt"
CREDENTIALS="${OSS_DIR}/credentials.enc"

# 1. Binary must actually run (not merely be present/executable).
if [[ ! -x "$OSS_DECRYPT" ]]; then
    echo "Decrypt CLI is not installed at ${OSS_DECRYPT}." >&2
    echo "Run /oss:login to install it." >&2
    exit 1
fi

VERSION_STDERR=$("$OSS_DECRYPT" --version 2>&1 >/dev/null)
if ! "$OSS_DECRYPT" --version >/dev/null 2>&1; then
    echo "Decrypt CLI is not runnable — it failed to start:" >&2
    echo "${VERSION_STDERR}" >&2
    echo "The binary is installed but crashes. Re-run /oss:login to reinstall." >&2
    exit 1
fi

# 2. Credentials must have been generated by --setup (present AND non-empty).
if [[ ! -s "$CREDENTIALS" ]]; then
    echo "Decrypt CLI credentials are not configured (${CREDENTIALS} missing or empty)." >&2
    echo "'--setup' did not complete. Re-run /oss:login to configure credentials." >&2
    exit 1
fi

echo "✅ Decrypt CLI verified: binary runs and credentials are configured."
exit 0
